SINGLE_INT_BYTES = 0.size
SINGLE_INT_BITS = SINGLE_INT_BYTES * 8
FIXNUM_MAX = 2**(SINGLE_INT_BITS - 2) - 1
FIXNUM_MIN = -FIXNUM_MAX - 1

# Concise code
FIXNUM_MAX = 2**(0.size * 8 - 2) - 1
FIXNUM_MIN = -FIXNUM_MAX - 1