---
inherit_from:
- .rubocop-disables.yml

AllCops:
  Exclude:
    - 'tmp/*.rb'
    - 'vendor/**/*'

Naming/AccessorMethodName:
  Enabled: false
  
Style/ParallelAssignment:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false

Metrics/MethodLength:
  Enabled: false

Style/WordArray:
  Enabled: false

Style/StringLiterals:
  Enabled: false
