---
inherit_from:
- .rubocop-disables.yml

AllCops:
  Exclude:
    - 'tmp/*.rb'
    - 'vendor/**/*'

Style/AccessorMethodName:
  Enabled: false
  
Style/ParallelAssignment:
  Enabled: false

Style/MethodCallWithoutArgsParentheses:
  Enabled: false
